config/routes.rb
Rails.application.routes.draw do
	root to: 'photos#feed'
	devise_for :users
  	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  	
=begin
  	scope '/user/:user_id' do
  		resources :photos, only: [:index, :new, :create]
  		resources :albums, only: [:index, :new, :create]
  	end
  	resources :photos, only: [:show, :edit, :update, :destroy]
  	resources :albums, only: [:show, :edit, :update, :destroy]
=end
	get 'photos/all', to: 'photos#all'

  	resources :photos
  	resources :albums
  	get 'users/follower', to: 'users#follower_index_private_profile'
  	get 'users/following', to: 'users#following_index_private_profile'

  	# public profile (user A watch user B's profile)
	scope '/users/:user_id' do
		get 'photos', to: 'photos#public_index'
		get 'albums', to: 'albums#public_index'
		get 'follower', to: 'users#follower_index_public_profile'
		get 'following', to: 'users#following_index_public_profile'
	end


  	scope '/admin' do
  		get 'photos', to: 'admins#photos_index'
  		get 'albums', to: 'admins#albums_index'
  		get 'users', to: 'admins#users_index'
  	end

  	get '/users/follow/:user_id', to: 'users#follow'
  	get '/users/unfollow/:user_id', to: 'users#unfollow'

  	scope '/likes/:model_type' do
  		get 'like/:post_id', to: 'likes#like'
  		get 'unlike/:post_id', to: 'likes#unlike'
  	end
end

app/models/album.rb
class Album < ApplicationRecord
	validates :title, presence: true, length: { maximum: 140 }
	validates :description, presence: true, length: { maximum: 300 }
	validates :sharing_mode, presence: true

	enum sharing_mode: {public_mode: 0, private_mode: 1}
	has_many :likes, as: :liked_on
	belongs_to :user
	has_many :photos, dependent: :destroy
	accepts_nested_attributes_for :photos
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_action :authenticate_user!, except: [:all, :show]

	def all
		@albums = Album.all
	end

	def index
		@albums = Album.where(user_id: current_user.id)
		@photos_count = Photo.where(user_id: current_user.id).count
		@albums_count = Album.where(user_id: current_user.id).count
		@followings_count = Relationship.where(follower_id: current_user.id).count
		@followers_count = Relationship.where(followed_id: current_user.id).count
	end

	def public_index
		@albums = Album.where(user_id: params[:id])
	end

	def show
		@album = Album.find(params[:id])
		respond_to do |format|
		    format.html
		    format.json {render json: @album}
		end
	end

	def create
		param = album_params()
		album = current_user.albums.create() do |u|
			u.title = param[:title]
			u.description = param[:description]
			u.sharing_mode = param[:sharing_mode]
			u.images = param[:images]
		end
		if album.valid?
			flash[:notice] = 'album created successfully'
		else
			flash[:error] = 'Failed to create album'
		end

		redirect_to albums_path
	end

	def new
		@albums = Album.new
	end

	def edit
		@album = Album.find(params[:id])
	end

	def update
		@album = Album.find(params[:id])
	   	is_succeed = @photo.update(album_params)
	   	if is_succeed == true
	   		flash[:notice] = 'Album updated successfully'
		else
			flash[:error] = 'Failed to update album'
	   	end

	   	redirect_to albums_path
	end

	def destroy
		album = Album.find(params[:id])
		album.destroy

		redirect_to albums_path
	end

	private
	def album_params
		params.require(:album).permit(:title, :sharing_mode, :description, {images: []}, :is_continue)
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.html.erb
<% if type == "private_profile" %>
	<%= content_tag :div, class: "col-3 mt-3 text-center post", id: "#{album.id}" do %>
	    <div class="card mt-3 border-0">
	    	<% (1..3).each do |i| %>
	    		<%= image_tag album.images[0].thumb.url, class: "img-thumbnail img image-stacked", size: "150x150" %>
	    	<% end %>
	      	<% if album.sharing_mode == "private_mode" %>
		      	<div class="card-img-overlay d-flex justify-content-center align-items-center" id="private-icon">
		        	<i class="fas fa-lock"></i>
		      	</div>
	      	<% end %>
	      	<div class="card-img-overlay album-description">
              <h5><%= album.images.size %><br><small>PHOTOS</small></h5>
            </div>  
	      	<div class="card-img-overlay bottom-right-pos">
	            <%= link_to 'Edit', edit_album_path(album.id), class: "btn edit-album-btn rounded-pill" %>
	        </div>
	      	<%= content_tag :p, truncate(album.title, length: 20, separator: ' ') %>
	    </div>
	<% end %>
<% elsif type == "public_profile" %>
	<%= content_tag :div, class: "col-3 mt-3 text-center post", id: "#{album.id}" do %>
	    <div class="card mt-3 border-0">
	      	<% (1..3).each do |i| %>
	    		<%= image_tag album.images[0].thumb.url, class: "img-thumbnail img image-stacked", size: "150x150" %>
	    	<% end %>
	    	<div class="card-img-overlay album-description">
              <h5><%= album.images.size %><br><small>PHOTOS</small></h5>
            </div>  
	      	<%= content_tag :p, truncate(album.title, length: 20, separator: ' ') %>
	    </div>
	<% end %>
<% end %>

app/views/albums/_form.html.erb
<div class="mt-4 mb-3">
  <% if album.new_record? == false %>
    <div class="d-flex justify-content-between">
      <h5 class="font-weight-bold"><%= form_title %></h5>
      <%= link_to "Back", albums_path, class: "btn navbar-theme text-white", id: "back-btn" %>
    </div>
  <% else %>
    <h5 class="font-weight-bold"><%= form_title %></h5>
  <% end %>
</div>
<hr class="horizontal-break">
<%= form_with model: album ,html: {class: 'photo-form', id: "photo-form"} do |form| %>
  <div class="row">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label :title, "Title", class: 'fw-bold' %>
        <%= form.text_field :title, value: album.new_record? ? nil : album.title ,class: "w-100", placeholder: "Album Title"%>
      </div>
      <div class="mb-3">
        <%= form.label :sharing_mode, "Sharing Mode", class: 'fw-bold w-100' %>
        <%= form.select :sharing_mode, options_for_select([["Public", "public_mode"], ["Private", "private_mode"]], album.new_record? ? "public_mode" : album.sharing_mode), {}, {class: "w-25"} %>
      </div>
      <div class="mb-3" id="image-area">
        <div class="d-flex">
          <% if album.new_record? %>
            <%= button_tag nil, class: "add-photo-btn rounded", type: "upload-image", id: "upload-image-btn" do %>
              <i class="fas fa-plus fa-3x plus-color"></i>
            <% end %>
          <% else %>
              <% album.images.each do |avatar| %>
                <%= hidden_field :photo, :images, multiple: true, value: avatar.identifier %>
                <div class="position-relative">
                  <%= image_tag avatar.image.url, size: "200x200" %>
                  <div class="position-absolute cancel-icon">
                  <i class="fas fa-times"></i>
                  </div>
                </div>
              <% end %>
          <% end %>
        </div>
      </div>
      <div class="mb-3">
        <%= form.file_field :images, class: 'invisible', multiple: true %>
        <%= hidden_field_tag 'file-size' %>
      </div>
      <div class="mb-3">
        <%= form.submit 'Save', {class: "btn btn-success", data: {disable_with: false}, id: "save-btn"} %>
        <% if is_edit == true %>
          <%= link_to album_path(album), method: :delete, class: "btn btn-danger ms-5", id: "delete-btn", data: { confirm: "Are you sure?" } do %>
            <i class="fas fa-trash-alt"></i> Delete
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <div>
        <%= form.label :description, "Description", class: 'fw-bold' %>
        <%= form.text_area :description, rows: 5, class: "w-100", value: album.new_record? ? nil : album.description, placeholder: "Photo Description" %>
      </div>
    </div>
  </div>
<% end %>
<div class="modal" id="modal-dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <p>Are you finished?</p>
      </div>
      <div class="modal-footer">
        <%= link_to 'No', '#', method: :post , class: "btn btn-secondary" %>
        <%= link_to 'Yes', 'albums/', method: :post, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/albums/edit.html.erb
<div class="col-2 text-center">
  <%= render "/shared/user-sidebar" %>
</div>
<div class="col-8 bg-white">
  <div class="album-edit-page" id="album-edit-page">
    <%= render 'form', form_title: "Edit Album", album: @albums, is_edit: true %>
  </div>
</div>
<div class="col-2"></div>

<%= javascript_pack_tag 'upload-image-form.js' %>

app/views/albums/index.html.erb
<div class="col-2 text-center">
  <%= render "/shared/user-sidebar" %>
</div>
<div class="col-8 bg-white">
  <div class="private-profile" id="private-profile">
    <%= render "shared/user-profile", type: "private_profile", current_view: "album", photos_count: @photos_count, albums_count: @albums_count, followings_count: @followings_count, followers_count: @followers_count %>
    <div class="add-photo-div">
      <%= link_to 'Add Album', new_album_path, class: "btn btn-success float-end" %>
    </div>
    <div class="row">
      <%= @albums.each do |a| %>
        <%= render "album", album: a, type: "private_profile" %>
      <% end %>
    </div>
  </div>
</div>
<div class="col-2"></div>
<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<%= render "shared/modal", type: "album" %>
<%= javascript_pack_tag 'album-modal.js' %>

app/views/albums/new.html.erb
<div class="col-2 text-center">
  <%= render "/shared/user-sidebar" %>
</div>
<div class="col-8 bg-white">
  <div class="album-new-page" id="album-new-page">
    <%= render 'form', form_title: "New Album", album: @albums, is_edit: false %>
  </div>
</div>
<div class="col-2"></div>

<%= javascript_pack_tag 'upload-image-form.js' %>