config/routes.rb
Rails.application.routes.draw do
	root to: 'photos#feed'
	devise_for :users
  	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  	
=begin
  	scope '/user/:user_id' do
  		resources :photos, only: [:index, :new, :create]
  		resources :albums, only: [:index, :new, :create]
  	end
  	resources :photos, only: [:show, :edit, :update, :destroy]
  	resources :albums, only: [:show, :edit, :update, :destroy]
=end
	get 'photos/all', to: 'photos#all'

  	resources :photos
  	resources :albums
  	get 'users/follower', to: 'users#follower_index_private_profile'
  	get 'users/following', to: 'users#following_index_private_profile'

  	# public profile (user A watch user B's profile)
	scope '/users/:user_id' do
		get 'photos', to: 'photos#public_index'
		get 'albums', to: 'albums#public_index'
		get 'follower', to: 'users#follower_index_public_profile'
		get 'following', to: 'users#following_index_public_profile'
	end


  	scope '/admin' do
  		get 'photos', to: 'admins#photos_index'
  		get 'albums', to: 'admins#albums_index'
  		get 'users', to: 'admins#users_index'
  	end

  	get '/users/follow/:user_id', to: 'users#follow'
  	get '/users/unfollow/:user_id', to: 'users#unfollow'

  	scope '/likes/:model_type' do
  		get 'like/:post_id', to: 'likes#like'
  		get 'unlike/:post_id', to: 'likes#unlike'
  	end
end

app/models/photo.rb
class Photo < ApplicationRecord
	enum sharing_mode: {public_mode: 0, private_mode: 1}
	has_many :likes, as: :liked_on
	belongs_to :user
	belongs_to :album, optional: true
	mount_uploader :image, ImageUploader

	validates :title, presence: true, length: { maximum: 140 }
	validates :description, presence: true, length: { maximum: 300 }
	validates :sharing_mode, presence: true
	validates :image, presence: true ,file_size: { less_than: 5.megabytes }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!, except: [:all, :show]

	def all
		@photos = Photo.all
	end

	def feed
		@photos = Photo.includes(:user).where(user_id: Relationship.where(follower_id: current_user.id).pluck(:followed_id))
	end

	def index
		@photos = Photo.where(user_id: current_user.id)
		@user = current_user
		@photos_count = Photo.where(user_id: current_user.id).count
		@albums_count = Album.where(user_id: current_user.id).count
		@followings_count = Relationship.where(follower_id: current_user.id).count
		@followers_count = Relationship.where(followed_id: current_user.id).count
	end

	def public_index
		@photos = Photo.where(user_id: params[:user_id])
		@user = User.find(params[:user_id])
		@photos_count = Photo.where(user_id: @user.id).count
		@albums_count = Album.where(user_id: @user.id).count
		@followings_count = Relationship.where(follower_id: @user.id).count
		@followers_count = Relationship.where(followed_id: @user.id).count
		@is_following = Relationship.exists?(follower_id: current_user.id, followed_id: params[:user_id])
	end

	def show
		@photo = Photo.find(params[:id])
		respond_to do |format|
		    format.html
		    format.json {render json: @photo}
		end
	end

	def create
		param = photo_params()
		photo = current_user.photos.create() do |u|
			u.title = param[:title]
			u.description = param[:description]
			u.sharing_mode = param[:sharing_mode]
			u.image = param[:image]
		end
		if photo.valid?
			flash[:notice] = 'Photo created successfully'
		else
			flash[:error] = 'Failed to create photo'
		end

		redirect_to photos_path
	end

	def new
		@photo = Photo.new
	end

	def edit
		@photo = Photo.find(params[:id])
	end

	def update
		@photo = Photo.find(params[:id])
	   	is_succeed = @photo.update(photo_params)
	   	if is_succeed == true
	   		flash[:notice] = 'Photo updated successfully'
		else
			flash[:error] = 'Failed to update photo'
	   	end

	   	redirect_to photos_path
	end

	def destroy
		photo = Photo.find(params[:id])
		photo.destroy

		redirect_to photos_path
	end

	private
	def photo_params
		params.require(:photo).permit(:title, :sharing_mode, :description, :image)
	end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<div class="mt-4 mb-3">
  <% if photo.new_record? == false %>
    <div class="d-flex justify-content-between">
      <h5 class="font-weight-bold"><%= form_title %></h5>
      <%= link_to "Back", photos_path, class: "btn navbar-theme text-white", id: "back-btn" %>
    </div>
  <% else %>
    <h5 class="font-weight-bold"><%= form_title %></h5>
  <% end %>
</div>
<hr class="horizontal-break">
<%= form_with model: photo ,html: {class: 'photo-form', id: "photo-form"} do |form| %>
  <div class="row">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label :title, "Title", class: 'fw-bold' %>
        <%= form.text_field :title, value: photo.new_record? ? nil : photo.title ,class: "w-100", placeholder: "Photo Title"%>
      </div>
      <div class="mb-3">
        <%= form.label :sharing_mode, "Sharing Mode", class: 'fw-bold w-100' %>
        <%= form.select :sharing_mode, options_for_select([["Public", "public_mode"], ["Private", "private_mode"]], photo.new_record? ? "public_mode" : photo.sharing_mode), {}, {class: "w-25"} %>
      </div>
      <div class="mb-3" id="image-area">
        <div class="d-flex">
          <% if photo.new_record? %>
            <%= button_tag nil, class: "add-photo-btn rounded", type: "upload-image", id: "upload-image-btn" do %>
              <i class="fas fa-plus fa-3x plus-color"></i>
            <% end %>
          <% else %>
              <div class="position-relative">
                <%= image_tag photo.image.url, size: "200x200" %>
                <div class="position-absolute cancel-icon">
                  <i class="fas fa-times"></i>
                </div>
              </div>
          <% end %>
        </div>
      </div>
      <div class="mb-3">
        <%= form.file_field :image, class: 'invisible' %>
        <%= hidden_field_tag 'file-size' %>
      </div>
      <div class="mb-3">
        <%= form.submit 'Save', {class: "btn btn-success", data: {disable_with: false}} %>
        <% if photo.new_record? == false %>
          <%= link_to photo_path(photo), method: :delete, class: "btn btn-danger ms-5", id: "delete-btn", data: { confirm: "Are you sure?" } do %>
            <i class="fas fa-trash-alt"></i> Delete
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <div>
        <%= form.label :description, "Description", class: 'fw-bold' %>
        <%= form.text_area :description, rows: 5, class: "w-100", value: photo.new_record? ? nil : photo.description, placeholder: "Photo Description" %>
      </div>
    </div>
  </div>
<% end %>

app/views/photos/_photo-card.html.erb
<%= content_tag :div, class: "col-6", id: "post-#{photo.id}" do %>
  <div class="shadow card mt-2">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= image_tag photo.image.thumb.url, class: "card-img post", id: photo.id %>
      </div>
      <div class="col-md-8">
        <div class="card-body h-100 d-flex flex-column justify-content-between">
          <div>
            <div class="card-title">
              <% avatar_generate_url = "https://ui-avatars.com/api/?name=" + user.first_name + "+" + user.last_name %>
              <%= image_tag( user.avatar.file.nil? ? avatar_generate_url : user.avatar.url, size: "50x50", class: "rounded-circle") %>
              <span class="text-blue-facebook fw-bold ml-2"><%= user.first_name + " " + user.last_name %></span>  
            </div>
            <%= content_tag :h5, truncate(photo.title, length: 27, separator: ' '), class: "card-title fw-bold" %>
            <%= content_tag :p, truncate(photo.title, length: 187, separator: ' '), class: "card-text card-content" %>
          </div>
          <div>
            <div class="d-flex justify-content-between">
              <% is_already_liked = Like.exists?(user_id: current_user.id, liked_on_id: photo.id, liked_on_type: "Photo") %>
              <%= content_tag :div, class: "card-text like-btn", data: {post_id: photo.id, like_action: is_already_liked ? 'unlike' : 'like', model_type: 'Photo'} do %>
                <% if is_already_liked %>
                  <i class="fas fa-heart text-blue-facebook"></i>
                <% else %>
                  <i class="far fa-heart text-blue-facebook"></i>
                <% end %>
                <span class="text-blue-facebook" id="like-count-text"><%= photo.like_count %></span>  
              <% end %>
              <p class="card-text"><small class="text-muted"><%= photo.created_at %></small></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<% if type == "private_profile" %>
	<%= content_tag :div, class: "col-3 mt-3 text-center post", id: "#{photo.id}" do %>
	    <div class="card mt-3 border-0">
	      	<%= image_tag photo.image.thumb.url, class: "img", size: "300x300" %>
	      	<% if photo.sharing_mode == "private_mode" %>
		      	<div class="card-img-overlay d-flex justify-content-center align-items-center" id="private-icon">
		        	<i class="fas fa-lock"></i>
		      	</div>
	      	<% end %>
	      	<div class="card-img-overlay bottom-right-pos">
	            <%= link_to 'Edit', edit_photo_path(photo.id), class: "btn edit-photo-btn rounded-pill" %>
	        </div>
	      	<%= content_tag :p, truncate(photo.title, length: 20, separator: ' ') %>
	    </div>
	<% end %>
<% elsif type == "public_profile" %>
	<%= content_tag :div, class: "col-3 mt-3 text-center post", id: "#{photo.id}" do %>
	    <div class="card mt-3 border-0">
	      	<%= image_tag photo.image.thumb.url, class: "img" %>
	      	<%= content_tag :p, truncate(photo.title, length: 20, separator: ' ') %>
	    </div>
	<% end %>
<% end %>

app/views/photos/all.html.erb
<div class="col-2 text-center">
  <%= render "/shared/user-sidebar" %>
</div>
<div class="col-8 bg-white">
  <div class="feed" id="feed">
    <%= render "shared/photo-album-navigation" %>
    <div class="row">
      <%= @photos.each do |p| %>
        <%= render "photo-card", photo: p, user: User.find(p.user_id) %>
      <% end %>
    </div>
  </div>
</div>
<div class="col-2"></div>

<%= render "shared/modal", type: "photo" %>
<%= javascript_pack_tag 'photo-modal.js' %>
<%= javascript_pack_tag 'like-feature.js' %>

app/views/photos/edit.html.erb
<div class="col-2 text-center">
  <%= render "/shared/user-sidebar" %>
</div>
<div class="col-8 bg-white">
  <div class="photo-edit-page" id="photo-edit-page">
    <%= render 'form', form_title: "Edit Photo", photo: @photo %>
  </div>
</div>
<div class="col-2"></div>

<%= javascript_pack_tag 'upload-image-form.js' %>

app/views/photos/feed.html.erb
<div class="col-2 text-center">
  <%= render "/shared/user-sidebar" %>
</div>
<div class="col-8 bg-white">
  <div class="feed" id="feed">
    <%= render "shared/photo-album-navigation" %>
    <div class="row">
      <%= @photos.each do |p| %>
        <%= render "photo-card", photo: p, user: User.find(p.user_id) %>
      <% end %>
    </div>
  </div>
</div>
<div class="col-2"></div>

<%= render "shared/modal", type: "photo" %>
<%= javascript_pack_tag 'photo-modal.js' %>
<%= javascript_pack_tag 'like-feature.js' %>

app/views/photos/index.html.erb
<div class="col-2 text-center">
  <%= render "/shared/user-sidebar" %>
</div>
<div class="col-8 bg-white">
  <div class="private-profile" id="private-profile">
    <%= render "shared/user-profile", type: "private_profile", current_view: "photo", photos_count: @photos_count, albums_count: @albums_count, followings_count: @followings_count, followers_count: @followers_count, user: @user %>
    <div class="add-photo-div">
      <%= link_to 'Add Photos', new_photo_path, class: "btn btn-success float-end" %>
    </div>
    <div class="row">
      <%= @photos.each do |p| %>
        <%= render "photo", photo: p, type: "private_profile" %>
      <% end %>
    </div>
  </div>
</div>
<div class="col-2"></div>
<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<%= render "shared/modal", type: "photo" %>
<%= javascript_pack_tag 'photo-modal.js' %>

app/views/photos/new.html.erb
<div class="col-2 text-center">
  <%= render "/shared/user-sidebar" %>
</div>
<div class="col-8 bg-white">
  <div class="photo-new-page" id="photo-new-page">
    <%= render 'form', form_title: "New Photo", photo: @photo %>
  </div>
</div>
<div class="col-2"></div>

<%= javascript_pack_tag 'upload-image-form.js' %>

app/views/photos/public_index.html.erb
<div class="col-2 text-center">
  <%= render "/shared/user-sidebar" %>
</div>
<div class="col-8 bg-white">
  <div class="private-profile" id="private-profile">
    <%= render "shared/user-profile", type: "public_profile", current_view: "photo", photos_count: @photos_count, albums_count: @albums_count, followings_count: @followings_count, followers_count: @followers_count, is_following: @is_following, user: @user %>
    <div class="add-photo-div">
      <%= link_to 'Add Photos', new_photo_path, class: "btn btn-success float-end" %>
    </div>
    <div class="row">
      <%= @photos.each do |p| %>
        <%= render "photo", photo: p, type: "public_profile" %>
      <% end %>
    </div>
  </div>
</div>
<div class="col-2"></div>

<%= render "shared/modal", type: "photo" %>
<%= javascript_pack_tag 'photo-modal.js' %>
<%= javascript_pack_tag 'follow-feature.js' %>